apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: staging
  labels:
    app: product-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: 535537926657.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "staging"
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: staging
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP