version: '3.8'

services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    ports:
      - "8125:8125/udp"
      - "8126:8126"
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "datadog-agent"}]'

  # Update existing services to include DataDog labels
  user-service:
    build:
      context: ./applications/user-service
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=user-service
      - DD_ENV=development
      - DD_VERSION=1.0.0
    labels:
      com.datadoghq.ad.logs: '[{"source": "nodejs", "service": "user-service"}]'
    depends_on:
      - datadog

  product-service:
    build:
      context: ./applications/product-service
    environment:
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=product-service
      - DD_ENV=development
      - DD_VERSION=1.0.0
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "product-service"}]'
    depends_on:
      - datadog