global:
  scrape_interval: 30s  # Reduced frequency
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9000']
    metrics_path: '/metrics'
    scrape_interval: 30s