apiVersion: v1
kind: Namespace
metadata:
  name: artifactory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
        ports:
        - containerPort: 8081
        - containerPort: 8082
        env:
        - name: ENABLE_MIGRATION
          value: "y"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: artifactory-data
          mountPath: /var/opt/jfrog/artifactory
      volumes:
      - name: artifactory-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: artifactory
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    name: artifactory
  - port: 8081
    targetPort: 8081
    name: router
  selector:
    app: artifactory